name: "christoph-rumpel.com"
description: "Passionate web-developer and Laravel artisan from Vienna"
url: "http://christoph-rumpel.com"
exclude: ['README.md', 'sass/']
paginate: 8
paginate_path: /blog/page/:num
markdown: redcarpet
permalink: /:year/:month/:title
highlighter: pygments
gems: [jekyll-paginate]
